### ISSUE TITLE
cannot find the scp_plot_sc_2d function

### ISSUE THREAD

**Issue by yigerenbenpao** [xgrau/placozoa-cell-type-evolution-code#1]
I found that you use the scp_plot_sc_2d in results_scatlas/s06_postscatlas_it0_2021-12-16.R, but cannot find the function of scp_plot_sc_2d. Could you send me the code of this function ?

**Comment by xgrau** [comment]
Hi yigerenbenpao, I've just added it to the [scripts/helper.R](https://github.com/xgrau/placozoa-cell-type-evolution-code/blob/b7ad441e8ffe219c3c57d5c97000b1c6ea58ed70/scripts/helper.R#L850) script. Thanks for noticing this oversight.

Cheers,

Xavier

**Comment by yigerenbenpao** [comment]
Hi, Xavier, glad to receive your reply. Thank you for adding this function to script. Additionally, I also cannot find the Downstream_functions.R script. so, can you ?   ᵔ◡ᵔ   @xgrau

**Comment by yigerenbenpao** [comment]
and the Gene_module_functions.R script @xgrau

**Comment by xgrau** [comment]
Oh, that's unfortunate. All functions in these scripts should be in the `helper.R` source script though. Please let me know if something specific is missing (as it was the case with `scp_plot_sc_2d`).

**Comment by yigerenbenpao** [comment]
Thanks for you kind reply. emm... Have a little problem, such as gmod_runWGCNA function in s01_gmod_analysis_2022-08-22.R and gmod_plotMCheatmap_annotate_modules in s02_gmod_annotation_2022-08-22.R are also missing.

**Comment by xgrau** [comment]
Dammit, I forgot to add all gene module-related functions. Done now.

**Comment by yigerenbenpao** [comment]
Thank you so much, looking forward to see more fantastic project from you.
