### ISSUE TITLE
Have no similarity among a lot of metacell

### ISSUE THREAD

**Issue by yigerenbenpao** [xgrau/placozoa-cell-type-evolution-code#2]
Dear Xavier，I can run the metacell pipeline with your kind help, but there are a lot of metacell have no similarity, I could not understand this result, do you have any suggesstions ?
[metacell.scp.pdf](https://github.com/xgrau/placozoa-cell-type-evolution-code/files/14079479/metacell.scp.pdf)

**Comment by xgrau** [comment]
This looks more like and issue with the metacell algorithm than related to our project with placozoans, so I'd refer you to the [metacell project for further reference](https://github.com/tanaylab/metacell) — or are you trying to replicate our results with our data?

In my experience, this sort of 2D visualisation does not always reflect metacell-metacell similarity very well. You'd be well advised to check the co-clustering matrix directly, or tweak the co-clustering parameters, i.e. the `p_resamp` and `n_resamp` parameters in [`metacell::mcell_coclust_from_graph_resamp`](https://rdrr.io/github/tanaylab/metacell/man/mcell_coclust_from_graph_resamp.html).
