### ISSUE TITLE
cannot find the function "mcell_import_scmat_kallisto" in metacell

### ISSUE THREAD

**Issue by Ldabao233** [xgrau/placozoa-cell-type-evolution-code#4]
when I run the "s04_filter_cells_clicktag_samples_2021-11-16.R", I encountered an issue:
Error in mcell_import_scmat_kallisto(mat_nm = basename(ctmat_fn), matrix_fn = sprintf("%s/genes.mtx",  : function "mcell_import_scmat_kallisto" not found.
And I couldn't find this function in "help.R" either.

**Comment by xgrau** [comment]
I've added the function to the `helper.R` script. It should work now! Thanks for the headsup.

**Comment by Ldabao233** [comment]
Thank you for your timely reply! There is no problem with this step😄, but there is still a small issue, the "mcell_importscmat_10x_custom" function is not yet available. Could you please add it again? Thank you!!

**Comment by Ldabao233** [comment]
> Thank you for your timely reply! There is no problem with this step😄, but there is still a small issue, the "mcell_importscmat_10x_custom" function is not yet available. Could you please add it again? Thank you!!

I found this function in metacell "scmat_10x.r", maybe my metacell version is not the latest. Sorry to bother you.

**Comment by xgrau** [comment]
This one shoud work!

**Comment by Ldabao233** [comment]
When I continued to work on it, the "sca_mc_gene_counts_noobj" and "sca_mc_gene_counts" function were not found and I also did not find it in any R packages. Could you please add it again?
